id: '431'
project: ''

redis:
  host: '192.168.20.169'
  port: 6379
  db: 4
  password:
  max_connections: 2000
  decode_responses: true


storage:
  type: 'mongodb'
  batch_size: 1
  uri: 'mongodb://192.168.20.169:27017/'
  database_name: ''
  collection_name: ''